//REACT
import React from 'react'

//NEXT
import Head from 'next/head'
import Link from 'next/link'

//STYLE
import styled from 'styled-components'

//CONTEXT
import {useAuthContext} from '../AuthProvider'




export default function Home() {

  const {isLoggedIn, logout}:any = useAuthContext()

  return (
    <Container>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <Navbar>

          {isLoggedIn ?
            <>
              <Link href='/profile'>
                <a>Profile</a>
              </Link>
              <Link href='/cars'>
                <a>Cars</a>
              </Link>
              <button onClick={logout}>
                Logout
              </button>
            </>
          :
            <>
              <Link href='/register'>
                <a>Register</a>
              </Link>
              <Link href='/login'>
                <a>Login</a>
              </Link>
            </>
          }
        
        </Navbar>
    </Main>

    <Footer>
      <p>Footer</p>
    </Footer>
  </Container>
    
  )
}

//STYLED COMPONENTS
const Container = styled.div`
  min-height: 100vh;
  padding: 0 0.5rem;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  height: 100vh;
`;

const Main = styled.main`
  display: flex;
  width: 100%;
  height: 100%;
`;

const Navbar = styled.div`
  flex: 10%;
  height: 50px;
  display: flex;
  justify-content: space-evenly;
`;

const Footer = styled.footer`
  width: 100%;
  height: 100px;
  border-top: 1px solid #eaeaea;
  display: flex;
  justify-content: center;
  align-items: center;
`;
